### ISSUE TITLE
GTK Apps don't launch

### ISSUE THREAD

**Issue by ghost** [qmlos/shell#102]
I think this is probably a well-known issue, but I'm struggling to run Gtk application:
I've tried Chromium and Atom(from official pacman repos), while liri-shell and its dependencies are installed from the unstable repo.

This is Chromium error:
`[754:754:0510/161054.696148:ERROR:browser_main_lopp.cc(279)] Gtk: cannot open display:`
And this is the Atom error:
`(electron:765): Gtk-WARNING **: cannot open display:`

I understand that if Chrome doesn't work Atom won't either since it's based on chromium, but is there a fix planned for this issue? Is this an upstream bug of Wayland? 

My system Specs, if needed:
Virtualization: QEMU
vCPU: 4 cores (native is AMD FX6300)
Native OS: Ubuntu 16.04
GPU: GT 730, using QXL Video 16MiB

Comment if you need more specs, in the mean time I'll try the same packages on my arch Linux native installation.

**Comment by plfiorini** [comment]
QtWaylandCompositor doesn't support xdg_shell v6 yet although they are working on it, this means Gtk+ apps can't run as native Wayland clients.

XWayland support for Liri is now much more complete and enabled by default so Gtk+ apps can now run as XWayland clients.
