### ISSUE TITLE
error while loading shared libraries: libQt5Xdg.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by pegasusearl** [qmlos/shell#118]
I don't know if this is the right place to post it but since I can't found anywhere else, here we go.

I'm using antergos, I'm installing Liri from repository below
```
[liri-unstable]
SigLevel = Optional TrustAll
Server = https://repo.liri.io/archlinux/unstable/$arch/
```
following guide [here](https://wiki.archlinux.org/index.php/Liri).

I can't log in into liri session via GDM. and when I tried to start `liri-session` from TTY I got this message:
`/bin/liri-shell: error while loading shared libraries: libQt5Xdg.so.2: cannot open shared object file: No such file or directory`

I'm sorry If I didn't post it in the right place or post it properly.

**Comment by plfiorini** [comment]
Looks like libqtxdg soname changes with the library version which is now `3.1.0` thus making a rebuild of our packages necessary.

Now the rebuild is done I can't reproduce the problem anymore.
