### ISSUE TITLE
/bin/liri-shell: symbol lookup error: /bin/liri-shell: undefined symbol: _ZN4Liri6Logind15prepareForSleepEb

### ISSUE THREAD

**Issue by pegasusearl** [qmlos/shell#121]
Hello, this is a follow up post from https://github.com/lirios/shell/issues/118.
So I updated liri-shell-git **some time after the issue was closed**, the last problem is solved.
But there is another problem:

output of `liri-session` :
`/bin/liri-shell: symbol lookup error: /bin/liri-shell: undefined symbol: _ZN4Liri6Logind15prepareForSleepEb`

> I'm using antergos, I'm installing Liri from repository below
> ```
> [liri-unstable]
> SigLevel = Optional TrustAll
> Server = https://repo.liri.io/archlinux/unstable/$arch/
> ```
> following guide [here](https://wiki.archlinux.org/index.php/Liri).

Thank you

**Comment by plfiorini** [comment]
Fixed with a new build of the packages.
