### ISSUE TITLE
Non-liri wayland programs often fallback to XWayland

### ISSUE THREAD

**Issue by oxy** [qmlos/shell#129]
GTK3 applications fail with:
```
Gdk-WARNING **: <timestamp>: The Wayland compositor does not provide any supported shell interface, not using Wayland display
```

SDL2 on gzdoom fails with
```
Could not initialize SDL video:
The video driver did not add any displays
```

VLC opens in wayland when `DISPLAY` is unset, but shows as an undecorated window. 

Tested on Arch, gtk3 version 3.22.30-1 (gnome-screenshot, gzdoom file dialogs), SDL2 2.0.8-8 (gzdoom), vlc version 3.0.1-2.

**Comment by plfiorini** [comment]
This is partially connected with #146 because we don't support xdg-shell v6 or xdg-shell stable yet.

**Comment by plfiorini** [comment]
Turns out Gtk+ 3 is still using xdg-shell v6 which is supported by QtWayland 5.11, so we don't need xdg-shell stable that is provided by QtWayland 5.12.
