### ISSUE TITLE
Build Failure?

### ISSUE THREAD

**Issue by SolarAquarion** [qmlos/shell#130]
ERROR: /home/solaraquarion/build/liri-shell-git/src/shell/src/imports/launcher/launcher.qbs:3:1 Error while handling product 'launcherplugin':
/home/solaraquarion/build/liri-shell-git/src/shell/src/imports/launcher/launcher.qbs:13:5 Dependency 'Qt5GSettings' not found for product 'launcherplugin'.
/home/solaraquarion/build/liri-shell-git/src/shell/src/compositor/compositor.qbs:4:1 Error while handling product 'liri-shell':
/home/solaraquarion/build/liri-shell-git/src/shell/src/compositor/compositor.qbs:16:5 Dependency 'Qt5GSettings' not found for product 'liri-shell'.
/home/solaraquarion/build/liri-shell-git/src/shell/src/imports/launcher/launcher.qbs:3:1 Error while handling product 'launcherplugin':
/home/solaraquarion/build/liri-shell-git/src/shell/src/imports/launcher/launcher.qbs:17 Can't find variable: Qt5Xdg

**Comment by plfiorini** [comment]
Can't reproduce the issue, it seems like you are missing the dependencies.

**Comment by SolarAquarion** [comment]
I have the dependencies on my system though
