### ISSUE TITLE
qt.qpa.plugin issue

### ISSUE THREAD

**Issue by sushanthkumar2004** [qmlos/shell#157]
I'm using arch linux and I followed the instructions on https://liri.io/download/ to install. liri-session does not work from the tty, or GDM. When I run liri-session on tty, this is what I get: 

```
qt.qpa.plugin: Could not load the Qt platform plugin "liri" in "" even though it was found. 
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: liri, eglfs, linuxfb, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted
```

When I try logging via GDM, the screen turns black and sends me back to the login screen.

**Comment by pkoretic** [comment]
@plfiorini any idea on this one? I tried running it also as `liri-session -platform wayland` from inside weston but throws erros that it cannot find a wayland window.
`eglfs` platform also didn't work although I never thought about trying that on normal linux :)

**Comment by plfiorini** [comment]
@fractal2001 There were issues with the package, if you build the AUR packages now it should be working fine.
@pkoretic This is fixed now:
![screenshot from 2019-01-12 18-40-25](https://user-images.githubusercontent.com/843710/51076514-99f09900-1699-11e9-8be3-2952f3075f72.png)
