### ISSUE TITLE
cmake build generation fails on Liri1WaylandClient

### ISSUE THREAD

**Issue by ysblokje** [qmlos/shell#182]
Hi,
I am trying to build build the shell on ArchLinux but it fails on 

`CMake Error at src/helper/CMakeLists.txt:9 (find_package):
  By not providing "FindLiri1WaylandClient.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Liri1WaylandClient", but CMake did not find one.
`

I've been trying to search for it but can't find  Liri1WaylandClient.cmake either.

**Comment by plfiorini** [comment]
Added a dep on `liri-wayland-git` but I didn't have time to do a full build yesterday, so I'm not sure it works now.

**Comment by ysblokje** [comment]
I did an update of `liri-wayland-git` and tried to build `liri-shell-git`  and at the very least it build. 
Thanks.

**Comment by plfiorini** [comment]
Thanks for testing!
