### ISSUE TITLE
liri1platformheaders-config.cmake not found

### ISSUE THREAD

**Issue by ahmadraniri1994** [qmlos/shell#216]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior
After compile other dependencies liri-shell will be compiled succesfully.

## Current Behavior

Liri-shell complains that liri1platformheaders-config.cmake not found, I don't know where to loo..

## Possible Solution
Re-Trace other dependencies.
## Context

How has this issue affected you? What are you trying to accomplish?
Providing context helps us come up with a solution that is most useful in the real world.

## Environment

Include as many relevant details about the environment you experienced the bug in.

* Version used: Master or this repo.
* Operating system and version: Debian sid
* Device (phone, tablet, laptop, desktop, ...): Asus PRO36S
* CPU, RAM, screen resolution: intel i7-2620M (4) @ 3.400GHz, 4GB RAM, Resolution : 1366x768

**Comment by plfiorini** [comment]
Install the eglfs module (https://github.com/lirios/eglfs).
The dependency was not listed in README.md, it will be added soon.

**Comment by ahmadraniri1994** [comment]
Is polkit and solid repo still accessible ?

**Comment by plfiorini** [comment]
> Is polkit and solid repo still accessible ?

They appears to have recently changed.
A few seconds ago, I have update them in README.md.
