### ISSUE TITLE
Exit dialogs are confuzing

### ISSUE THREAD

**Issue by zigapk** [qmlos/shell#41]
After testing the shell I noticed that when user tries to leave the shell, it says "Your computer will shutdown/logout/something else in N seconds.". That is completley fine. However, the OK button lets user think that after clicking it, he will be able to continue to work for the remaining amount of time. That is just my opinion, but I think it would be better to change OK buttons to " shutdown/logout/something else NOW".

**Comment by plfiorini** [comment]
+1
