### ISSUE TITLE
Replace Q_FOREACH with C++ 11 range loop

### ISSUE THREAD

**Issue by plfiorini** [qmlos/shell#52]
http://doc.qt.io/qt-5/qtglobal.html#Q_FOREACH

**Comment by eyelash** [comment]
see also the discussion in lxde/lxqt#1060

**Comment by plfiorini** [comment]
Issue moved to [qmlos/qmlos #4](https://github.com/qmlos/qmlos/issues/4) via [**ZenHub**](https://www.zenhub.com/)
