### ISSUE TITLE
Remove the misc plugin and move needed stuff to Fluid

### ISSUE THREAD

**Issue by iBeliever** [qmlos/shell#55]
- KeyEventFilter seems to be in GreenIsland now
- Formatting stuff can go to Fluid
- StandardPaths is already in Fluid

**Comment by iBeliever** [comment]
Hmm, the problem with moving the formatting stuff to Fluid is that KFormat is GPLv2+ and Fluid is MPL.

**Comment by iBeliever** [comment]
libqmlos is LGPL, so we can't put the formatting stuff there either.

**Comment by plfiorini** [comment]
*1 for libqmlos

**Comment by iBeliever** [comment]
@plfiorini We'd have to relicense libqmlos as GPL though, right?

**Comment by plfiorini** [comment]
@iBeliever KFormat is LGPL 2+, Formats is GPL but is just a wrapper on a KFormat instance on the stack.
Another reason why Formats was created could be that KFormat is a gadget (I don't remember if it has problems with QML).

I would just delete Formats and make KFormat usable from QML.

**Comment by plfiorini** [comment]
Or we can make our QML wrapper in the QML plugin.
