### ISSUE TITLE
Make the shell work again

### ISSUE THREAD

**Issue by plfiorini** [qmlos/shell#6]
Latest changes broke the shell:

- [x] Windows are not displayed anymore
- [x] Panel doesn't show icons
- [x] Drawer doesn't resize to contents
- [x] Shortcuts don't work anymore
- [ ] Panel can't be moved anymore
- [ ] Panel size cannot be changed anymore

**Comment by iBeliever** [comment]
@plfiorini Both the issues should be fixed now. Have you found any other features broken by my refactoring?

**Comment by plfiorini** [comment]
Not sure if it's related to the refactoring but the drawer width is supposed to adapt to the contents width and it doesn't do it anymore.

**Comment by plfiorini** [comment]
@iBeliever Updated the todo list

**Comment by plfiorini** [comment]
Move panel improvements to M3 because it's not a priority.
I want to get something in shape for M2 even if it's earlier than expected.
