### ISSUE TITLE
Laggy mouse issue

### ISSUE THREAD

**Issue by teaalltr** [qmlos/shell#79]
The mouse movements are really laggy. May be due to mouse access overhead?

**Comment by plfiorini** [comment]
@Piruzzolo Bare metal or virtual machine?

**Comment by teaalltr** [comment]
Bare metal on a Lenovo G510, LiriOS as of 2017/01/08. I'll try more recent builds soon

**Comment by plfiorini** [comment]
@Piruzzolo does it still happen with the latest build?

Intel GPU?

**Comment by ctnlaring** [comment]
Googling the machine shows an AMD Radeon HD 8750M, A dual core cpu, and 4G of ram. Maybe just an optimization thing?

**Comment by plfiorini** [comment]
Closing. Please reopen if you can reproduce it again.
